auctions/urls.py
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required

from auctions.views import (
	IndexView, get_categories,
	CreateView, home,
	get_category, close_bid,
	ListingView, EditView,
	modify_watchlist, post_bid
)


app_name = 'auctions'

urlpatterns = [
	path("", home, name="home"),
	path("active-listings", IndexView.as_view(), name="index"),
	path("categories", get_categories, name="categories"),
	path("create", login_required(CreateView.as_view(), login_url="users:login"), name="create"),
	re_path("^edit/listing/(?P<id>[0-9]+)/$", login_required(EditView.as_view(), login_url="users:login"), name="edit"),
	path("category/<str:name>", get_category, name="category"),
	re_path("^listing/(?P<id>[0-9]+)/$", ListingView.as_view(), name="listing"),
	path("close/<int:list_id>", close_bid, name="close"),
	path("modify/<int:list_id>", modify_watchlist, name="modify_watchlist"),
	path("bid/<int:list_id>", post_bid, name="bid"),

]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls")),
    path("", include("users.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from users.views import (
	LoginView,
	RegisterView,
	logout_view,
	EditSittingsView,
	owned_list, watch_list
)


app_name = 'users'

urlpatterns = [
	path("login", LoginView.as_view(), name="login"),
	path("logout", logout_view, name="logout"),
	path("register", RegisterView.as_view(), name="register"),
	path("settings", login_required(EditSittingsView.as_view(), login_url="users:login"), name="settings"),
	path("lists/me", owned_list, name="mylists"),
	path("watch-lists/me", watch_list, name="watchlist"),
]

auctions/models.py
from django.db import models


class ActiveListings(models.Model):
	title         = models.CharField(max_length=64, null=False, blank=False, unique=True)
	price         = models.DecimalField(max_digits=13, decimal_places=2, null=False, blank=False)
	description   = models.TextField(null=False, blank=False)
	state         = models.BooleanField(default=True)
	created_at    = models.DateTimeField(auto_now_add=True)
	image_url     = models.URLField(max_length=1024, unique=True, null=True, blank=True)
	category      = models.ForeignKey('Category', on_delete=models.CASCADE, related_name='list', null=True, blank=True)
	user          = models.ForeignKey('users.User', related_name='created', on_delete=models.CASCADE, null=True, blank=True)


	class Meta:
		verbose_name = "activeListing"
		verbose_name_plural = "ActiveListings"

	def __str__(self):
		return self.title


class Category(models.Model):
	name  = models.CharField(max_length=64, null=False, blank=False, unique=True)


	class Meta:
		verbose_name = "category"
		verbose_name_plural = "Categories"

	def __str__(self):
		return self.name


class Bid(models.Model):
	nbids   = models.IntegerField(default=0)
	listing = models.OneToOneField('ActiveListings', on_delete=models.CASCADE, related_name='bid_item', null=False, blank=False)
	winner = models.ForeignKey('users.User', on_delete=models.CASCADE, related_name='bid_winner', null=True, blank=True)

	class Meta:
		verbose_name = "Bid"
		verbose_name_plural = "Bids"

	def __str__(self):
		return f'bid number: {self.id}'

auctions/forms.py
from django import forms 
from .models import (
	ActiveListings
)


class ActiveListingsForm(forms.ModelForm):
	class Meta:
		model = ActiveListings
		fields = ('title', 'price', 'description', 'category', 'image_url',)


class EditListingsForm(forms.ModelForm):
	class Meta:
		model = ActiveListings
		fields = ('title', 'description', 'category', 'image_url',)

auctions/views.py
from django.views.generic import View
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_http_methods
from django.shortcuts import render, redirect
from django.contrib import messages
from decimal import Decimal
from .forms import (
    ActiveListingsForm, EditListingsForm
)
from .models import (
    ActiveListings, Category, Bid
)
from users.models import (
    User, Comments
)


def home(request):
    template_name = "auctions/index.html"
    active_lists = ActiveListings.objects.all()
    return render(request, template_name, {"lists": active_lists})


class IndexView(View):
    template_name = "auctions/index.html"

    def get(self, request, *args, **kwargs):
        active_lists = ActiveListings.objects.filter(state=True).all()
        return render(request, self.template_name, {"lists": active_lists})


class CreateView(View):
    template_name = "auctions/create.html"

    def get(self, request, *args, **kwargs):
        form = ActiveListingsForm()
        return render(request, self.template_name, {"form": form})

    def post(self, request, *args, **kwargs):
        form = ActiveListingsForm(request.POST)

        if form.is_valid():
            instance = form.save(commit=False)
            category_name = form.cleaned_data['category']
            if not category_name:
                category = Category.objects.get(name='unknown')
                instance.category = category

            user = User.objects.get(username=request.user)
            instance.user = user
            instance.save()
            bid = Bid(listing=instance)
            bid.save()
            messages.success(request, "Listing has been created successfully. create another one?")
            form = ActiveListingsForm()
            return render(request, self.template_name, {"form": form})

        return render(request, self.template_name, {"form": form})


class EditView(View):
    template_name = "auctions/edit.html"

    def get(self, request, *args, **kwargs):
        listing = ActiveListings.objects.get(pk=kwargs['id'])
        if request.user == listing.user:
            form = EditListingsForm(initial={
                "title": listing.title,
                "description": listing.description,
                'category': listing.category,
                "image_url": listing.image_url,
            })
            return render(request, self.template_name, {"form": form, "list": listing})
        else:
            return HttpResponse('error 505: forbidden go back to <a href="/"> Home </a>.')

    def post(self, request, *args, **kwargs):
        listing = ActiveListings.objects.get(pk=kwargs['id'])
        form = EditListingsForm(request.POST, instance=listing)

        if form.is_valid():
            category_name = form.cleaned_data['category']
            if not category_name:
                category = Category.objects.get(name='unknown')
                listing.category = category
            form.save()
            return redirect('auctions:listing', id=kwargs['id'])

        return render(request, self.template_name, {"form": form, "list": listing})


@method_decorator(login_required, name='post')
class ListingView(View):
    template_name = "auctions/listing.html"

    def get(self, request, *args, **kwargs):
        listing = ActiveListings.objects.get(pk=kwargs['id'])
        comments = Comments.objects.filter(listing=listing).all()
        bid = Bid.objects.get(listing=listing)
        if request.user.is_authenticated:
            user = User.objects.get(username=request.user)
            watch_lists = user.watched_list.all()
            return render(request, self.template_name, {
                "list": listing, "comments": comments, "watch_lists": watch_lists, "bid": bid
            })
        return render(request, self.template_name, {
            "list": listing, "comments": comments, "bid": bid
        })

    def post(self, request, *args, **kwargs):
        list_id = request.POST['list-id']
        user = User.objects.get(username=request.user)
        listing = ActiveListings.objects.get(id=list_id)
        comments = Comments.objects.filter(listing=listing).all()
        description = request.POST['comment']

        if len(description) <= 0:
            messages.error(request, "invalid empty comment")
            return render(request, self.template_name, {
                "list": listing,
                "comments": comments
            })
        else:
            comment = Comments(description=description, listing=listing, user=user)
            comment.save()

        return redirect('auctions:listing', id=list_id)


def get_category(request, name):
    template_name = 'auctions/index.html'
    category = Category.objects.get(name=name)
    lists = ActiveListings.objects.filter(category=category).all()
    return render(request, template_name, {"lists": lists})


def get_categories(request):
    template_name = 'auctions/categories.html'
    categories = Category.objects.all()
    return render(request, template_name, {"categories": categories})


@login_required(login_url="users:login")
def close_bid(request, list_id):
    listing = ActiveListings.objects.get(pk=list_id)
    if request.user == listing.user:
        listing.state = False
        listing.save()
        return redirect('auctions:index')
    else:
        return HttpResponse('error 505: forbidden go back to <a href="/"> Home </a>.')


@login_required(login_url="users:login")
def modify_watchlist(request, list_id):
    listing = ActiveListings.objects.filter(pk=list_id)
    state = request.GET['state']
    user = User.objects.get(username=request.user.username)
    watch_lists = user.watched_list.all()

    if listing[0] in watch_lists and state == "False":
        user.watched_list.set(user.watched_list.difference(listing))
        user.save()
    elif listing[0] not in watch_lists and state == "True":
        user.watched_list.set(watch_lists.union(listing))
        user.save()
    return redirect('auctions:listing', id=list_id)


@require_http_methods('POST')
@login_required(login_url="users:login")
def post_bid(request, list_id):
    listing = ActiveListings.objects.get(pk=list_id)

    if request.POST['bid'] != "":
        price = Decimal(request.POST['bid'])
        if price > listing.price:
            bid = Bid.objects.get(listing=listing)
            listing.price = price
            bid.winner = request.user
            bid.nbids += 1
            listing.save()
            bid.save()
            messages.success(request, "bid has successfully added!")
            return redirect('auctions:listing', id=list_id)
        else:
            messages.error(request, f"bid must be more than {listing.price}$")
            return redirect('auctions:listing', id=list_id)
    else:
        messages.error(request, "bid must have a value")
        return redirect('auctions:listing', id=list_id)

auctions/templates/auctions/categories.html
{% extends "layout.html" %}
{% block title %}Categories{% endblock %}

{% block main %}
    <ul class="list-group">
      {% for category in  categories%}
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <a href="{% url 'auctions:category' category.name %}">{{category.name}}</a>
          <span class="badge badge-primary badge-pill">{{category.list.count}}</span>
        </li>
      {% endfor %}
    </ul>
{% endblock %}




auctions/templates/auctions/create.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}

{% block title %}
    create
{% endblock %}



{% block main %}

  {% include "message.html" %} 
      
  <h3>Create New Listing</h3>
  <hr>
    {% if message %}
        <div class="error">{{ message }}</div>
    {% endif %}

<form action="{% url 'auctions:create' %}" method="POST">
	<table>
		{% crispy form %}
	</table>
  <input class="btn btn-warning" type="submit" value="Create">

</form>
	<hr>
{% endblock %}




auctions/templates/auctions/edit.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}

{% block title %}
    edit
{% endblock %}

{% block main %}

  {% include "message.html" %} 
      
  <hr>
    {% if message %}
        <div class="error">{{ message }}</div>
    {% endif %}
<form action="{% url 'auctions:edit' list.id %}" method="POST"> {% csrf_token %}
	<table>
		{% crispy form %}
	</table>
  <input class="btn btn-warning" type="submit" value="Save edit">

</form>
<hr>
{% endblock %}


auctions/templates/auctions/index.html
{% extends "layout.html" %}
{% load static %}

{% block title %}Dashboard{% endblock %}

{% block css %} <link href="{% static 'auctions/main.css' %}" rel="stylesheet"> {% endblock %}

{% block main %}
    <h2>Active Listings</h2>
<div class="row">
{% for list in lists%}
   <a href="{% url 'auctions:listing' list.id %}" style="color: black; text-decoration: none;">
	<div class="col-sm-12 col-md-6 col-lg-4 p-2">
		<div class="card">
			{% if  list.image_url %}
				<img class="card-img-top" src="{{list.image_url}}" alt="Card image cap">
			{% else %}
				<img class="card-img-top" src="https://www.triequestrian.ie/pub/media/catalog/product/placeholder/default/No-images-placeholder_1.png" alt="Card image cap">
			{% endif %}

		  <div class="card-body">
		    <h5 class="card-title p-0 m-0 col-12 text-truncate">{{list.title|safe}}</h5>
		  </div>
		  <ul class="list-group list-group-flush">
		  	
		    <li class="list-group-item py-1 px-2 m-0"><h6 class="d-inline">Status: </h6>
		    	{% if list.state %}
		    		<span class="text-success">opened</span>
		    	{% else %}
		    		<span class="text-danger">closed</span>
		    	{% endif %}
		    </li>
		  	<li class="list-group-item py-1 px-2 m-0"><h6>Currently: {{list.price|safe}}$</h6></li>
		  	<li class="list-group-item py-1 px-2 m-0"><small>Created by: </small>{{list.user.username}}</li>
		  	<li class="list-group-item py-1 px-2 m-0"><small>Created at: </small>{{list.created_at}}</li>
		    <li class="list-group-item py-1 px-2 m-0"><small>Category: </small><a href="{% url 'auctions:category' list.category.name %}" class="card-link">{{list.category|safe}}</a></li>	    
		  </ul>
		</div>
	  </div>
   </a>
<!-- in case ther is no active listings-->
{% empty %}
	<hr>
   	<h3>sorry!! there are no lists now</h3>
   	<hr>
{% endfor %}
</div>
{% endblock %}

auctions/templates/auctions/listing.html
{% extends "layout.html" %}
{% block title %} {{list.title}} {% endblock %}

{% block main %}
{% include "message.html" %}

<div class="row">
<div class="col-sm-12 col-md-4 col-lg-4 mx-auto p-2">
	<div class="card" style="width: 18rem;">
		{% if  list.image_url %}
			<img class="card-img-top" src="{{list.image_url}}" alt="Card image cap">
		{% else %}
			<img class="card-img-top" src="https://www.triequestrian.ie/pub/media/catalog/product/placeholder/default/No-images-placeholder_1.png" alt="Card image cap">
		{% endif %}

		<div class="card-body">
		    <h5 class="card-title p-0 m-0 col-12 text-truncate">{{list.title|safe}}</h5>
		  </div>
		  <ul class="list-group list-group-flush">
		  	
		    <li class="list-group-item py-1 px-2 m-0"><h6 class="d-inline">Status: </h6>
		    	{% if list.state %}
		    		<span class="text-success">opened</span>
		    	{% else %}
		    		<span class="text-danger">closed</span>
		    	{% endif %}
		    </li>
		  	<li class="list-group-item py-1 px-2 m-0"><h6>Currently: {{list.price|safe}}$</h6></li>
		  	<li class="list-group-item py-1 px-2 m-0"><small>Created by: </small>{{list.user.username}}</li>
		  	<li class="list-group-item py-1 px-2 m-0"><small>Created at: </small>{{list.created_at}}</li>
		    <li class="list-group-item py-1 px-2 m-0"><small>Category: </small><a href="{% url 'auctions:category' list.category.name %}" class="card-link">{{list.category|safe}}</a></li>	    
		  </ul>
	</div>
  </div>
  <div class="col-sm-12 col-md-9 col-lg-8 mx-auto p-2">
  	<div class="row card text-center">
  		<div class="card-header">
    		<b>Current Price</b>
  		</div>
	    <div class="card-body">
	      <h5 class="card-title">{{list.price|safe}}$</h5>
	      <p class="card-text">[{{list.bid_item.nbids}} bids]</p>
	    {% if list.state %}
	      	{% include "running-bid.html" %}
	    {% else %}
	      {% include "closed-bid.html" %}
	   {% endif %}
	   </div>
    </div>

	<div class="row mt-4 p-0">
      <div class="card-body ">
		<h5 class="card-title">description</h5>
		 <hr>
		 <p class="card-text">{{list.description|safe}}</p>
		 <hr>
	   </div>
     </div>
	</div>
  </div>
</div>

<div class="row mt-4 p-2">
	<div class="card col-12">
	  <div class="card-header flex d-flex">
			Comments
	  </div>
	  <div class="card-body">
	   {% for comment in  comments %}
	     <blockquote class="blockquote mb-0">
		  <header class="blockquote-footer">
		   by: {{comment.user.username|safe}} 
		   <cite> {{comment.created_at}}</cite></header>
		  <p>{{comment.description|safe}}</p>
		  </blockquote>
		{% empty %}
		<h3>no comments right now</h3>
	   {% endfor %}
	  </div>
	</div>
</div>
{% include "comment.html" %}
{% endblock %}