auctions/urls.py
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required

from auctions.views import (
	IndexView, get_categories,
	CreateView, home,
	get_category, close_bid,
	ListingView, EditView,
	modify_watchlist, post_bid
)


app_name = 'auctions'

urlpatterns = [
	path("", home, name="home"),
	path("active-listings", IndexView.as_view(), name="index"),
	path("categories", get_categories, name="categories"),
	path("create", login_required(CreateView.as_view(), login_url="users:login"), name="create"),
	re_path("^edit/listing/(?P<id>[0-9]+)/$", login_required(EditView.as_view(), login_url="users:login"), name="edit"),
	path("category/<str:name>", get_category, name="category"),
	re_path("^listing/(?P<id>[0-9]+)/$", ListingView.as_view(), name="listing"),
	path("close/<int:list_id>", close_bid, name="close"),
	path("modify/<int:list_id>", modify_watchlist, name="modify_watchlist"),
	path("bid/<int:list_id>", post_bid, name="bid"),

]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls")),
    path("", include("users.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from users.views import (
	LoginView,
	RegisterView,
	logout_view,
	EditSittingsView,
	owned_list, watch_list
)


app_name = 'users'

urlpatterns = [
	path("login", LoginView.as_view(), name="login"),
	path("logout", logout_view, name="logout"),
	path("register", RegisterView.as_view(), name="register"),
	path("settings", login_required(EditSittingsView.as_view(), login_url="users:login"), name="settings"),
	path("lists/me", owned_list, name="mylists"),
	path("watch-lists/me", watch_list, name="watchlist"),
]

commerce/templates/closed-bid.html
 <div class="col-12">
    <input type="text" class="form-control text-center bg-warning" id="message" name="message" readonly value="this bid is closed">
	{% if not bid.winner and not list.state %}
		<b class="text text-center">bid owner has closed this bid before anyone can share in</b>
	{% elif bid.winner == request.user and not list.state %}
	    <b class="text text-success text-center">Conrats!! you have won this bid</b>
	{% elif not list.state %}
	    <b class="text text-center">bid winner is: [{{bid.winner}}]</b>
   {% endif %}
</div>
{% if request.user.is_authenticated %}
	<div class="col-12">
		<form action="{% url 'auctions:modify_watchlist' list.id %}" method="GET">
			{% if list in watch_lists %}
				<input type="hidden" name="state" value="False">
				<button type="submit" id="watch-btn" style="width: 80%;" class="btn mt-4 btn btn-outline-danger">remove from watchlist</button> 
		   {% else %}
			    <input type="hidden" name="state" value="True">
			    <button type="submit" id="watch-btn" style="width: 80%;" class="btn mt-4 btn btn-outline-primary">Add to watchlist</button> 
		    {% endif %}  
		</form>
	</div>
{% endif %}

commerce/templates/comment.html
{% if request.user.is_authenticated %}
<div class="row mt-2 p-1 text-center">
   <form action="{% url 'auctions:listing' list.id %}", method="POST"> {% csrf_token %}
	<div class="form-group">
	  <label for="comment">Add your comment</label>
	  <textarea class="form-control" name="comment" id="comment" rows="6" cols="150"></textarea>
	</div>
	<input type="hidden" name="list-id" id="list-id" value="{{list.id}}">
	<button type="submit" style="width: 30%;" class="btn mt-4 btn btn-primary">comment</button>
   </form>
</div>
{% else %}
<div class="row mt-2 p-1 text-center">
	<h6>login to comment...</h6>
</div>
{% endif %}

commerce/templates/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">

    <head>

        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="author" content="Ahmed Hatem AbdelHamid">
        <meta name="description" content="an eBay-like e-commerce auction site that will allow users to post auction listings, place bids on listings, comment on those listings, and add listings to a “watchlist">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- documentation at http://getbootstrap.com/docs/4.1/, alternative themes at https://bootswatch.com/ -->
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet">

        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>

        <!-- https://favicon.io/emoji-favicons/money-mouth-face/ -->
        <link href="{% static 'icons/logo.ico' %}" rel="icon">
        {% block css %} {% endblock %}

        <title>Auctions: {% block title %}{% endblock %}</title>

    </head>

    <body>

        <nav class="navbar navbar-expand-md navbar-dark bg-dark text-white">
            <a class="navbar-brand" href="{% url 'auctions:home' %}">
                <span>
                <img src="{% static 'img/logo.png' %}" style="width: 60px; height: 60px;">
                </span><span>Auctions</span></a>
            <button aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-target="#navbar" data-toggle="collapse" type="button">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbar">
                <ul class="navbar-nav mr-auto mt-2">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auctions:index' %}">Active Listing</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auctions:categories' %}">Categories</a>
                    </li>
                    {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auctions:create' %}">Create Listing</a>
                    </li>
                    {% endif %}
                </ul>
                {% if request.user.is_authenticated %}
                    <ul class="navbar-nav ml-auto mt-2">
                       <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Profile
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                              <a class="dropdown-item" href="{% url 'users:watchlist' %}">Your WatchList</a>
                              <a class="dropdown-item" href="{% url 'users:mylists' %}">Your Listings</a>
                              <a class="dropdown-item" href="{% url 'users:settings' %}">settings</a>
                              <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
                            </div>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="" >
                              Signed in as {{request.user.username.title}}.
                          </a>
                        </li>
                    </ul>
                {% else %}
                    <ul class="navbar-nav ml-auto mt-2">
                        <li class="nav-item"><a class="nav-link" href="{% url 'users:register' %}">Register</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'users:login' %}">login</a></li>
                    </ul>
                {% endif %}
            </div>
        </nav>


        <main class="container p-5">
            {% block main %}{% endblock %}
        </main>

    </body>

</html>

commerce/templates/message.html
{% for message in messages %}
	{% if message.tags == "error" %}
		<div id="message" class="alert alert-danger mx-auto" style="width:100%;" role="alert">
     		<div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
		    <script type="text/javascript">
		        const div = document.querySelector("#message");
		          setTimeout(()=> {
		              div.remove();
		          }, 3000);
		    </script>
    	</div>
    {% elif message.tags == "success" %}
		<div id="message" class="alert alert-success mx-auto" style="width:100%;" role="alert">
     		<div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
		    <script type="text/javascript">
		        const div = document.querySelector("#message");
		          setTimeout(()=> {
		              div.remove();
		          }, 3000);
		    </script>
    	</div>
    {% else %}
		<div id="message" class="alert alert-warning mx-auto" style="width:100%;" role="alert">
     		<div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
		    <script type="text/javascript">
		        const div = document.querySelector("#message");
		          setTimeout(()=> {
		              div.remove();
		          }, 3000);
		    </script>
    	</div>
	{% endif %}	
{% endfor %}

commerce/templates/running-bid.html
{% if request.user.is_authenticated %}
<div class="forms row">
	<div class="col-12">
	  <form action="{% url 'auctions:bid' list.id %}" method="POST"> {% csrf_token %}
	    <div class="form-group">
		  <input type="number" class="form-control text-center" id="bid" name="bid" min="0" step="any">
		  <small id="emailHelp" class="form-text text-muted">enter more than {{list.price|safe}}$</small>
        </div>
	    <button type="submit" style="width: 50%;" class="btn btn-warning">Place bid</button>
	  </form>
	</div>
	<div class="col-12">
	   <form action="{% url 'auctions:modify_watchlist' list.id %}" method="GET">
		 {% if list in watch_lists %}
			<input type="hidden" name="state" value="False">
		    <button type="submit" id="watch-btn" style="width: 80%;" class="btn mt-4 btn btn-outline-danger">remove from watchlist</button>  
		  {% else %}
			  <input type="hidden" name="state" value="True">
		      <button type="submit" id="watch-btn" style="width: 80%;" class="btn mt-4 btn btn-outline-primary">Add to watchlist</button> 
		   {% endif %}  
	   </form>
	</div>
	<div class="col-12 flex d-flex justify-content-center">
	   {% if  request.user == list.user %}
	     <div class="row">
		    <div class="col-4 mr-4">
			  <form action="{% url 'auctions:edit' list.id %}" method="GET"> 
				<button type="submit" id="edit-btn" name="edit-btn"  class="btn mt-4 btn btn-primary">edit list</button> 
			  </form>
			</div>
			<div class="col-4 mr-4">
			 <form action="{% url 'auctions:close' list.id %}" method="GET">
			    <button type="submit" id="close-btn" name="close-btn"  class="btn mt-4 btn btn-danger">close bid</button> 
		      </form>
		     </div>
	     </div>
	   {% endif %}
   </div>
</div>
{% else %}
<div class="row">
 <div class="col-12">
    <input type="text" class="form-control text-center bg-warning" id="message" name="message" readonly value="login to share in this bid">
</div>
</div>
{% endif %}